name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: sparse clang-format
        version: 1.0

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run make all
      run: make all

    - name: Run make install
      run: sudo make install

    - name: Remove object files
      run: rm --force build/*.o

    - name: Create Tarball
      run: tar -cvzf libarg.tar.gz build/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libarg
        path: libarg.tar.gz
